// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { configDotenv } from 'dotenv';
configDotenv({ path: `${__dirname}/apps/main/.env` });

export default defineConfig({
  schema: 'apps/main/prisma/schema.prisma',
  migrations: {
    path: 'apps/main/prisma/migrations',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
